### ISSUE TITLE
Paradox Config crashes with LibCD 2.2.0+

### ISSUE THREAD

**Issue by LemmaEOF** [RedstoneParadox/paradox-config#1]
Paradox Config's LibCD integration still uses the [`ConditionalData.registerCondition`](https://github.com/RedstoneParadox/paradox-config/blob/master/src/main/java/redstoneparadox/paradoxconfig/conditions/ParadoxConfigConditions.kt#L17) method, which was deprecated in 2.0.0 and removed in 2.2.0. Registering conditions should now be done in a `LibCDInitializer#initConditions` block. I can send in a PR for this soon if you'd like.

**Comment by RedstoneParadox** [comment]
Fixed.
