### ISSUE TITLE
`fabric.mod.json` “Website” link leads to fabricmc.net, “Issues” link is empty

### ISSUE THREAD

**Issue by nok-ko** [RedstoneParadox/paradox-config#5]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/13428215/103103488-3df95380-45d6-11eb-9035-22fa71714416.png">

<img width="704" alt="image" src="https://user-images.githubusercontent.com/13428215/103103497-4d789c80-45d6-11eb-99fc-757246536cd8.png">

:)

**Comment by RedstoneParadox** [comment]
Fixed.
