### ISSUE TITLE
Upload to Modrinth instead of relying on Jitpack

### ISSUE THREAD

**Issue by triphora** [RedstoneParadox/paradox-config#6]
Jitpack can be quite unreliable at times, so I would suggest uploading to Modrinth and have people use their Maven instead of Jitpack:
`https://api.modrinth.com/maven`, and the artifact would be `maven.modrinth:paradoxconfig:<version>`
No need to have the exclude fapi/flk, just modApi and include, since it'd just be the jar for PC.

**Comment by RedstoneParadox** [comment]
Done.
